import {
  Dashboard,
  Growth,
  Currency,
  ToolKit,
  Delivery,
  Education,
  UserMultiple,
  Settings,
  Logout,
  ChevronRight,
  Add,
  Edit,
  TrashCan,
  Password,
  CircleDash,
  Home,
  Roadmap,
  Help,
  Bullhorn,
  Connect,
  LogoFacebook,
  AiGovernanceLifecycle,
  Chat,
  Bot,
  NetworkEnterprise,
  FlowStream,
} from '@carbon/icons-react'
import { ComponentType } from 'react'

export const iconMap: Record<string, ComponentType<{ size?: number; className?: string }>> = {
  'dashboard': Dashboard,
  'growth': Growth,
  'currency': Currency,
  'tool-kit': ToolKit,
  'delivery': Delivery,
  'education': Education,
  'user-multiple': UserMultiple,
  'settings': Settings,
  'logout': Logout,
  'chevron-right': ChevronRight,
  'add': Add,
  'edit': Edit,
  'trash-can': TrashCan,
  'password': Password,
  'circle-dash': CircleDash,
  'home': Home,
  'roadmap': Roadmap,
  'help': Help,
  'campaign': Bullhorn,
  'connect': Connect,
  'logo--facebook': LogoFacebook,
  'ai-governance-lifecycle': AiGovernanceLifecycle,
  'chat': Chat,
  'bot': Bot,
  'network-enterprise': NetworkEnterprise,
  'flow-stream': FlowStream,
}
